chain=test

ipcconnect=unix

# Template generation interval (in seconds)
sv2interval=30

# Delta fees to reach before sending new templates (in satoshis)
sv2feedelta=1000

debug=sv2
loglevel=sv2:trace
debug=ipc