[testnet4]
server=1
rpcuser=username
rpcpassword=password

# Performance tuning
dbcache=4096
maxmempool=300

# Useful indexes and networking
txindex=1
listen=1
debug=1

# Enable IPC for sv2-tp communication (also provided via cmd flag)
ipcbind=unix

# RPC settings (bind locally inside container)
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0