rpcuser=username
rpcpassword=password

server=1

testnet=1

txindex=1
listen=1
maxconnections=10
debug=1
debug=ipc

# Enable IPC for sv2-tp communication
ipcbind=unix

[test]
rpcport=18332
port=18333
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

zmqpubhashblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333